version: "3.3"

services:
  vb_mqtt_broker:
    build:
      context: ./vb_mqtt_broker
      dockerfile: Dockerfile
    image: vb-mqtt_broker:0.0.2
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/
    volumes:
      - vb_mqtt_broker:/vb_mqtt_broker
    command:
    ports:
      - 1883:1883
      - 8883:8883
