# Для запуска 'docker-compose up' .
version: "3.3"

# В этом разделе описаны различные контейнеры (службы).
services:
  
  rabbitmq:
    # Есть готовый оффициальный образ RabbitMQ;
    # https://hub.docker.com/_/rabbitmq/ для подробностей.
    image: 'rabbitmq: management-alpine'
    ports:
      # Стандартный порт протокола AMQP
      - ' 5672: 5672 '
      # Пользовательский интерфейс управления HTTP
      - ' 15672: 15672 '
    networks:
      - network

  consumer:
    # If needed, Docker Compose will automatically run consumer/Dockerfile.
    build: consumer

    # Переменная окружения:
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/

      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'

    # Опять же, запустите частную сеть. Необходимо увидеть "rabbitmq"
    # волшебное DNS-имя Docker.
    networks:
      - network

  publisher:
    # Идентично потребителю.
    build: publisher
    
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    
    networks:
      - network

networks:
  # Объявить нашу частную сеть. Мы должны объявить один за волшебство
  # Docker DNS для работы, но в остальном настройки по умолчанию в порядке.
  network: {}